
; Das Wemos D1 mini Board wird als Zielplattform definiert.
; Die einzelteile des Bouds weerden festgelegt.
; Als bedingung für die serielle Ausgabe wird festgelegt, dass die Ausgabe erst nach einem Zeilenumbruch gesendet wird.

[env:d1_mini]
platform = espressif8266
board = d1_mini
framework = arduino
monitor_filters = send_on_enter